package oauthbridge

import "html/template"

const consentCSS = `.consent-shell{width:min(560px,calc(100% - 32px));margin:0 auto;padding:7vh 0 48px}.consent-card{margin-top:24px;padding:clamp(24px,6vw,38px)}.connection{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:14px;margin:26px 0;padding:18px;border:1px solid var(--line);border-radius:16px;background:#091725}.connection-party{text-align:center;min-width:0}.connection-icon{display:grid;place-items:center;width:48px;height:48px;margin:0 auto 8px;border-radius:14px;background:#1a3045;color:var(--accent);font-weight:900}.connection-name{display:block;overflow-wrap:anywhere}.connection-arrow{color:var(--accent);font-size:1.5rem}.permission-list{display:grid;gap:10px;margin:20px 0}.permission{display:grid;grid-template-columns:28px 1fr;gap:12px;padding:13px;border:1px solid var(--line);border-radius:12px}.permission-check{color:var(--accent);font-weight:900}.permission strong{display:block}.permission span{color:var(--muted);font-size:.82rem}.boundary{margin:20px 0;padding:13px;border-left:3px solid var(--accent);background:#0a1928;color:#cbd8e5;font-size:.86rem}.decision-actions{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center}.decision-actions button{width:100%}.deny{background:transparent;color:var(--muted);border:1px solid var(--line)}.deny:hover{background:#172a3e;color:var(--text)}@media(max-width:520px){.connection{grid-template-columns:1fr}.connection-arrow{transform:rotate(90deg)}.decision-actions{grid-template-columns:1fr}.decision-actions .approve{grid-row:1}.decision-actions .deny{grid-row:2}}`

var consentTemplate = template.Must(template.New("consent").Parse(consentPage))

const consentPage = `<!doctype html><html lang='en'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Authorize access - RemoteOps</title><style nonce='{{.StyleNonce}}'>{{.CSS}}</style></head><body><main class='consent-shell'><div class='brand'><span class='brand-mark'>R</span><span>RemoteOps</span></div><section class='card consent-card'><p class='eyebrow'>Connection request</p><h1>Authorize access?</h1><p class='muted'>Review who is connecting and what they can do.</p><div class='connection'><div class='connection-party'><span class='connection-icon'>{{.ClientInitial}}</span><strong class='connection-name'>{{.Client}}</strong><span class='hint'>Application</span></div><span class='connection-arrow' aria-hidden='true'>→</span><div class='connection-party'><span class='connection-icon'>R</span><strong class='connection-name'>RemoteOps</strong><span class='hint'>MCP server</span></div></div><h2>Requested access</h2><div class='permission-list'>{{range .Permissions}}<div class='permission'><span class='permission-check' aria-hidden='true'>✓</span><div><strong>{{.Title}}</strong><span>{{.Description}}</span></div></div>{{end}}</div><p class='boundary'>Signed in as <strong>{{.Email}}</strong> with the <strong>{{.Role}}</strong> role. Authorization cannot increase this role or enable God Mode.</p><form method='post' action='/oauth/consent'><input type='hidden' name='transaction' value='{{.Transaction}}'><input type='hidden' name='csrf' value='{{.CSRF}}'><div class='decision-actions'><button class='deny' type='submit' name='decision' value='deny'>Cancel</button><button class='approve' type='submit' name='decision' value='approve'>Authorize connection</button></div></form></section></main></body></html>`
